DROP TABLE NEWDEPT CASCADE CONSTRAINTS;

CREATE TABLE NEWDEPT
(DEPTNO NUMBER(4) CONSTRAINT NEWDEPT_DEPTNO_PK PRIMARY KEY,
DNAME VARCHAR2(10),
LOC VARCHAR2(10));

INSERT INTO NEWDEPT SELECT * FROM MPSDEPT;

SELECT * FROM NEWDEPT;

DROP TABLE NEWEMP;

CREATE TABLE NEWEMP
(EMPNO NUMBER(4) CONSTRAINT NEWEMP_EMPNO_PK PRIMARY KEY,
ENAME VARCHAR2(10),
JOB CHAR(10),
MGR NUMBER(4),
HIREDATE DATE,
SAL NUMBER(9,2),
COMM NUMBER(9,2),
DEPTNO NUMBER(4),
CONSTRAINT NEWEMP_DEPTNO_FK
FOREIGN KEY (DEPTNO)
REFERENCES NEWDEPT(DEPTNO));

INSERT INTO NEWEMP SELECT * FROM MPSEMP;

SELECT * FROM NEWEMP;


DECLARE
	V_DNO NEWDEPT.DEPTNO%TYPE := &P_DEPTNO;   --30 , 77
	E_CHILD_ROWS_EXISTS EXCEPTION;  
	PRAGMA EXCEPTION_INIT     
		(E_CHILD_ROWS_EXISTS         , -02292);   
	V_COUNT NUMBER;
	CURSOR C1(P_DNO NEWEMP.DEPTNO%TYPE) IS SELECT ROWNUM RN , E.* FROM NEWEMP E WHERE DEPTNO = P_DNO;
BEGIN
	DELETE FROM NEWDEPT  -- PARENT TABLE
	WHERE DEPTNO = V_DNO;
	IF SQL%ROWCOUNT = 0 THEN  -- SQL IS IMPLICIT CURSOR AND ROWCOUNT IS ATTRIBUTE
		DOPL('NO SUCH DEPT EXISTS IN TABLE.');
	ELSIF SQL%ROWCOUNT > 0 THEN
		DOPL(SQL%ROWCOUNT || ' rows deleted.');
		COMMIT;
	END IF;  
EXCEPTION
	WHEN E_CHILD_ROWS_EXISTS THEN 
		DBMS_OUTPUT.PUT_LINE('CANNOT REMOVE DEPT ' || TO_CHAR(V_DNO) || ' FROM NEWDEPT TABLE AS BELOW EMPLOYEES WORKS IN IT. ');  
		DBMS_OUTPUT.PUT_LINE('SRNO. EMPNO ENAME       JOB');
		DBMS_OUTPUT.PUT_LINE(RPAD('=',36,'='));
		FOR ER IN C1(V_DNO) LOOP
			DBMS_OUTPUT.PUT_LINE(ER.RN || ' ' || 
			                     LPAD(ER.EMPNO,8) ||'  '||
								 RPAD(ER.ENAME,12) ||
								 ER.JOB);
		END LOOP;
		DBMS_OUTPUT.PUT_LINE(LPAD('=',36,'='));   
	WHEN OTHERS THEN
		DBMS_OUTPUT.PUT_LINE('OTHERS IS HANDLING THE EXCEPTION.');     
END; 
/
