-- EXAMPLE OF ERROR IN DECLARATION PART

DECLARE
	Y NUMBER := 'SITA';  -- CALLING ENVIRONMENT WILL HANDLE THE ERROR
BEGIN
	DBMS_OUTPUT.PUT_LINE('PARENT BLOCK BEGINS HERE.');
	DECLARE
		X NUMBER := 'RAM';  -- OUTER BLOCK WILL HANDLE THE ERROR
		A NUMBER;
	BEGIN
		A := 'LAXMAN';
		DBMS_OUTPUT.PUT_LINE(X);
	EXCEPTION
		WHEN OTHERS THEN
		    X := 'RAM';
			DBMS_OUTPUT.PUT_LINE('INNER BLOCK OTHERS.');
	END;
	DBMS_OUTPUT.PUT_LINE('THIS IS THE LAST LINE OF INNER BLOCK.');
EXCEPTION
--	NULL;
	WHEN OTHERS THEN
	    Y := 'SITA';
		DBMS_OUTPUT.PUT_LINE('OUTER BLOCK OTHERS.'); 
END;
/