-- PROPAGATION
<<PARENT>>BEGIN
/*
THIS ANONYMOUS BLOCK HAS SINGLE OUTER BLOCK AND TWO ENCLOSING BLOCK INSIDE IT.
WHEN FIRST INNER BLOCK RAISES SOME ERROR AND IF IT'S EXCEPTION PART HANDLES THE SAME
THE CONTROL WILL RESUME TO THE ENCLOSING BLOCK. IF IT DOES NOT HANDLE THE EXCEPTION THE 
CONTROL WILL PROPAGATES TO OUTER BLOCK.
*/
	--  FIRST INNER BLOCK STARTS HERE.
	DBMS_OUTPUT.PUT_LINE('THIS IS THE FIRST EXECUTABLE STATEMENT OF THE PARENT BLOCK.'||CHR(10));
	<<CHILD1>>DECLARE
		V_SAL MPSEMP.SAL%TYPE;
	BEGIN
		DBMS_OUTPUT.PUT_LINE('FIRST CHILD BLOCK BEGINS HERE.'||CHR(10));				
		SELECT SAL INTO V_SAL FROM MPSEMP WHERE EMPNO = 7789;  -- 7789
--		FOR X IN 1..100000000 LOOP
			NULL;
--		END LOOP;
		DBMS_OUTPUT.PUT_LINE('SALARY OF 7788 IS ' || V_SAL);
		<<CHILD>>
		DBMS_OUTPUT.PUT_LINE('FIRST CHILD BLOCK ENDS HERE.'||CHR(10)||CHR(10));		
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			DBMS_OUTPUT.PUT_LINE('FIRST BLOCK NO DATA FOUND');
--			RAISE;
--			GOTO CHILD; -- WE CAN'T MOVE TO EXCEPTION PART TO SAME BLOCK EXECUTABLE PART.
--			GOTO CHILD2; -- THIS IS POSSIBLE.
--			GOTO PARENT1;
		WHEN OTHERS THEN
			DBMS_OUTPUT.PUT_LINE('OTHERS OF FIRST ENCLOSING PART IS EXECUTED.');  
			RAISE_APPLICATION_ERROR(-20001,'EXECUTION WILL STOP HERE.');         
	END;
	DBMS_OUTPUT.PUT_LINE('THIS LINE IS PLACED BETWEEN ENCLOSING/ TWO CHILD BLOCKS.'||CHR(10));
	-- SECOND INNER BLOCK STARTS HERE.
	<<CHILD2>>DECLARE
		V_ENAME MPSEMP.ENAME%TYPE;
	BEGIN
		DBMS_OUTPUT.PUT_LINE('SECOND ENCLOSING BLOCK BEGINS HERE.'||CHR(10));		
		SELECT ENAME INTO V_ENAME FROM MPSEMP WHERE EMPNO = 7790;
		DBMS_OUTPUT.PUT_LINE('VALUE DISPLAYED FROM SECOND CHILD BLOCK ' ||V_ENAME);
		DBMS_OUTPUT.PUT_LINE('SECOND ENCLOSING BLOCK ENDS HERE.'||CHR(10));		
	EXCEPTION
		WHEN NO_DATA_FOUND THEN
			RAISE_APPLICATION_ERROR(-20008,'SECOND ENCLOSING BLOCK NO_DATA_FOUND RAISE APPLICATION ERROR.');     
			DBMS_OUTPUT.PUT_LINE('ENCLOSING BLOCK EXCEPTION PART EXECUTED.'||CHR(10));     
		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20008,'SECOND ENCLOSING BLOCK OTHERS RAISE APPLICATION ERROR.');     
--			DBMS_OUTPUT.PUT_LINE('ENCLOSING BLOCK OTHERS PART EXECUTED.'||CHR(10));     */
	END;
		<<PARENT1>>
		DBMS_OUTPUT.PUT_LINE('THIS IS THE LAST EXECUTABLE STATEMENT OF THE PARENT BLOCK.'||CHR(10));

EXCEPTION
      WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('OUTER BLOCK EXCEPTION NO DATA FOUND.');       
/*		WHEN OTHERS THEN
			RAISE_APPLICATION_ERROR(-20004,'OUTER BLOCK OTHERS RAISE APPLICATION ERROR.');     
			DBMS_OUTPUT.PUT_LINE('OUTER BLOCK OTHERS IS EXECUTED.');      */
END;
/