ACCEPT ENO PROMPT "TYPE EMPLOYEE NUMBER : "
REM ACCEPT NEW_COMM PROMPT "ENTER NEW COMMISSION : "
-- SUBSTITUTION VARIABLE OVERRIDES REMARK OR COMMENT AND SO WILL WAIT FOR THE VALUE.
BEGIN
	COMM_PACKAGE.RESET_COMM(&ENO , &&NEW_COMM);
--	COMM_PACKAGE.VALIDATE_COMM(777);  -- PRIVATE ITEM CAN'T BE CALLABLE FROM OUTSIDE PACKAGE
END;
/
UNDEF NEW_COMM
UNDEFINE ENO