-- PACKAGE SYNTAX IS DIFFERENT FROM SUB-PROGRAMS. IT DOESN'T HAVE 3 PARTS LIKE DECLARATION , BODY AND EXCEPTION HANDLING.
-- ALL ITEMS DECLARED IN PACKAGE SPECIFICATION IS PUBLIC. PUBLIC ITEMS ARE CALLABLE FROM ANY WHERE.
-- <<LABEL>> HERE LABEL IS NOT AVAILABLE.

--                        PACKAGE NAME
CREATE OR REPLACE PACKAGE COMM_PACKAGE  -- THIS IS SPEC PART OF PACKAGE WHICH HOLDS SPEC OF ALL PUBLIC ITEMS. 
IS  -- AS
	/* PUBLIC ITEM DECLARATION WHICH IS CALLABLE FROM ANY WHERE */
	G_MAX_COMM NUMBER := 555;  -- INITIALIZED GLOBAL/PUBLIC VARIABLE
	/*
	-- THESE ARE ALL DECLARATIVE ITEMS
	PI CONSTANT NUMBER := 3.14;
	CURSOR C101 IS SELECT * FROM EMPLOYEES;
	CHILD_RECORD_EXISTS EXCEPTION;
	PRAGMA EXCEPTION_INIT(USER DEFINED EXCEPTION NAME, ORACLE INTERNAL ERROR NUMBER);
	TYPE DREC IS RECORD 
	(DID NUMBER(3),
	 DNM VARCHAR2(20));
	TYPE IBT IS TABLE OF DEPARTMENTS%ROWTYPE INDEX BY PLS_INTEGER;
	TYPE NT IS TABLE OF DEPARTMENTS.DEPARTMENT_NAME%TYPE;
	TYPE VA IS VARRAY(5) OF DEPARTMENTS.DEPARTMENT_ID%TYPE;
	TYPE EMP_REFCSR IS REF CURSOR;
	*/
	--                                                 TRUE/FALSE
	--FUNCTION VALIDATE_COMM (P_COMM IN NUMBER) RETURN BOOLEAN;  -- SUB-PROGRAM SPECIFICATION
	PROCEDURE RESET_COMM (P_EMPNO MPSEMP.EMPNO%TYPE, P_COMM IN NUMBER);  -- PUBLIC PROCEDURE
	-- THE ABOVE TWO LINES ARE DECLARATION OR SPECIFICATIONS OF PUBLIC SUBPROGRAMS.
END COMM_PACKAGE;
/
-- <<LABEL>>