-- EXAMPLE OF DEFUALT PARAMETER VALUES 
DROP SEQUENCE DEPT_SEQ;
CREATE SEQUENCE DEPT_SEQ START WITH 50 INCREMENT BY 10;

CREATE OR REPLACE PROCEDURE ADD_DEPT
(P_DNAME MPSDEPT.DNAME%TYPE DEFAULT 'UNKNOWN',
P_LOC IN MPSDEPT.LOC%TYPE DEFAULT 'AHMEDABAD')
IS
BEGIN
	INSERT INTO MPSDEPT (DEPTNO , DNAME , LOC)
	VALUES (DEPT_SEQ.NEXTVAL , P_DNAME , P_LOC);
END;
/