CREATE OR REPLACE PROCEDURE QUERY_EMP 
	(P_EMPNO IN  MPSEMP.EMPNO%TYPE,  /* ACTUAL PARAMETER -> FORMAL PARAMETER */
	 P_ENAME OUT MPSEMP.ENAME%TYPE,  /* FORMAL PARAMETER -> ACTUAL PARAMETER */
	 P_SAL   OUT MPSEMP.SAL%TYPE, -- IF WE SEND VALUE FOR OUT PARAMTERS IT WILL SILENTLY IGNORE IT.
	 P_COMM  OUT MPSEMP.COMM%TYPE /* DEFAULT 100  ERROR */)
IS
BEGIN
/*	SELECT ENAME , COMM
	INTO P_ENAME , P_SAL , P_COMM
	FROM MPSEMP
	WHERE EMPNO = P_EMPNO;   */ -- AND COMM IS NULL;  
/*	UPDATE MPSEMP SET SAL = SAL * 1.20 WHERE EMPNO = P_EMPNO;  
	COMMIT; */
	DBMS_OUTPUT.PUT_LINE('SALARY VALUE FROM PROCEDURE : ' || NVL(TO_CHAR(P_SAL),'NO VALUE') || CHR(10));
	SELECT ENAME   , SAL   , COMM
	INTO   P_ENAME , P_SAL , P_COMM
	FROM MPSEMP
	WHERE EMPNO = P_EMPNO; -- AND COMM IS NULL; 
END;
/