/* STORED PROCEDURE */ 
CREATE OR REPLACE PROCEDURE GET_Z
(X NUMBER, Y IN OUT NUMBER , Z IN OUT NUMBER)
IS
BEGIN
--    Z := 4;
	Z := X / (Y-100);
	DBMS_OUTPUT.PUT_LINE('Z = ' || Z);  -- THIS STATEMENT WILL BE SKIPPED.
-- MAKE REMARK TO EXCEPTION PART AND SEE THE RESULT.
/*
EXCEPTION
	WHEN ZERO_DIVIDE THEN   -- SPECIFIC PRE-DEFINDED EXCEPTION
		DBMS_OUTPUT.PUT_LINE('YOU TRIED TO DIVIDE WITH ZERO IN GET_Z PROCEDURE.');     
	WHEN OTHERS THEN  -- GENERAL EXCEPTION
--		RAISE_APPLICATION_ERROR(-20999,' WHEN OTHERS OF GET_Z PROCEDURE IS EXECUTED.');   
		RAISE;  */
END;
/