DECLARE 
	V_EMPNO MPSEMP.EMPNO%TYPE := &ENO;  -- 7839
--	V_EMPNO DATE := SYSDATE;
	V_ENAME MPSEMP.ENAME%TYPE;
	V_SAL MPSEMP.SAL%TYPE DEFAULT 2000;
	V_COMM MPSEMP.COMM%TYPE;
BEGIN
	DBMS_OUTPUT.PUT_LINE('ORIGINAL VALUES BEFORE PROCEDURE CALL' || CHR(10));
	DBMS_OUTPUT.PUT_LINE('EMPNO      : ' || V_EMPNO);
	DBMS_OUTPUT.PUT_LINE('ENAME      : ' || V_ENAME);
	DBMS_OUTPUT.PUT_LINE('SALARY     : ' || V_SAL);
	DBMS_OUTPUT.PUT_LINE('COMMISSION : ' || NVL(V_COMM,0));
	QUERY_EMP(V_EMPNO , V_ENAME , V_SAL , V_COMM);
--            AP TO FP, FORMAL PARAMETER TO ACTUAL PARAMETER PASSING FOR REMAINING 3	
	DBMS_OUTPUT.PUT_LINE(CHR(10)||'UPDATED VALUES AFTER PROCEDURE CALL' ||CHR(10));
	DBMS_OUTPUT.PUT_LINE('EMPNO      : ' || V_EMPNO);
	V_ENAME := LOWER(V_ENAME);
	UPDATE MPSEMP SET SAL = V_SAL * 1.20 WHERE EMPNO = V_EMPNO; 
	COMMIT;
	SELECT SAL INTO V_SAL FROM MPSEMP WHERE EMPNO = V_EMPNO;
	DBMS_OUTPUT.PUT_LINE('ENAME      : ' || V_ENAME);  -- WILL DISPLAY MODIFIED VALUE
	DBMS_OUTPUT.PUT_LINE('NEW SALARY : ' || V_SAL);  -- WILL DISPLAY TABLE'S NEW VALUE
	DBMS_OUTPUT.PUT_LINE('COMMISSION : ' || NVL(V_COMM,0)); -- WILL DISPLAY VALUE RECEIVED FROM PROCEDURE
END;
/