DECLARE 
	PHONE VARCHAR2(13) /* NOT NULL */ := '&PHONE_NO';  -- 0123456789
BEGIN
	DBMS_OUTPUT.PUT_LINE('ORIGINAL PHONE NO. : ' || PHONE);
	FORMAT_PHONE(PHONE); -- 0123456789  -- ACTUAL TO FORMAL AND THEN FORMAL TO ACTUAL
	DBMS_OUTPUT.PUT_LINE('FORMATED PHONE NO. : ' || PHONE);
END;
/