-- ANONYMOUS / UN-NAMED BLOCK / CALLING PROGRAM / MAIN PROGRAM
DECLARE 
	V_ENO MPSEMP.EMPNO%TYPE := &ENO;  -- 7566
	C_INCR_PERC CONSTANT NUMBER(5,2) := &INCR_PERCENT;  -- 30
	V_SAL MPSEMP.SAL%TYPE;
BEGIN
	SELECT SAL INTO V_SAL FROM MPSEMP WHERE EMPNO = V_ENO;
	DBMS_OUTPUT.PUT_LINE('OLD SALARY OF EMPLOYEE NO. ' ||V_ENO||' IS ' || V_SAL);
--  RAISE_SALARY IS CALLED PROGRAM.	
	RAISE_SALARY(V_ENO , C_INCR_PERC);    -- ACTUAL PARAMETERS
--	RAISE_SALARY(V_ENO , 7.5 * POWER(2,2));    -- ACTUAL PARAMETERS
--	EXECUTE IMMEDIATE ('CREATE TABLE T1(NO  NUMBER)');
	SELECT SAL INTO V_SAL FROM MPSEMP WHERE EMPNO = V_ENO;
	DBMS_OUTPUT.PUT_LINE(CHR(10)||'NEW SALARY OF EMPLOYEE NO. ' ||V_ENO||' IS ' || V_SAL);
	ROLLBACK;
	SELECT SAL INTO V_SAL FROM MPSEMP WHERE EMPNO = V_ENO;
	DBMS_OUTPUT.PUT_LINE(CHR(10)||'OLD/NEW SALARY OF EMPLOYEE NO. ' ||V_ENO||' IS ' || V_SAL); 
EXCEPTION
	WHEN NO_DATA_FOUND THEN
		DOPL(V_ENO || ' DOESN''T WORK IN THE COMPANY.');
END;
/