-- FOR PARAMETERS HAVING DEFAULT VALUE IF WE SUPPLY VALUE AT THE TIME OF CALLING, OUR VALUES WILL BE USED OTHERWISE DEFAULT VALUES WILL BE USED.
BEGIN 
	ADD_DEPT; -- THIS PROCEDURE CALL WILL USE BOTH DEFAULT VALUES.
	ADD_DEPT();
	ADD_DEPT('TRAINING','PARIS'); -- POSITIONAL PARAMETER PASSING
	ADD_DEPT(P_LOC => 'LONDON' , P_DNAME => 'EDUCATION'); -- NAMED PARAMETER PASSING
--	ADD_DEPT(,'SINGAPORE'); -- ERROR
--  ADD_DEPT(DEFAULT,'SINGAPORE'); ERROR
	ADD_DEPT('','BANGKOK');
	ADD_DEPT(P_LOC => 'SINGAPORE'); -- HERE WE MUST HAVE TO USE NAMED PARAMETER PASSING STYLE.
	ADD_DEPT('HR');
--	ADD_DEPT('HR',DEFAULT); -- WE CAN'T USE DEFAULT PSEUDOCOLUMN IN PROCEDURE.
	ADD_DEPT('PURCHASE',NULL);
	ADD_DEPT('','');
	ADD_DEPT('',NULL);
	ADD_DEPT('&PRATIK','GOA');
	ADD_DEPT('IT',P_LOC => 'SINGAPORE');  -- COMBINATION
/*           POSITIONAL , NAMED ASSOCIATION	  */
END;
/