/*
CREATE A TRIGGER WHICH SHOULD NOT ALL ANY DML OPERATIONS IN MPSEMP TABLE.

ALLOWANCE :

1 MON-FRI
2 9AM-1PM AND 2PM-6PM
3 WORKING DAY (NOT HOLIDAY)

CREATE TABLE HOLIDAYS : HOLI_DATE , HOLIDAY_FOR

5 ROWS INSERT

HOLI_DATE HOLIDAY_FOR
26-JAN-24 REPUBLIC DAY
01-MAY-22 GUJRAT DAY
15-AUG-24 INDEPENDENCE DAY
14-NOV-21 CHILDREN DAY
25-DEC-24 CHRISTMAS
*/