-- EXAMPLE OF PARAMERISED CURSOR

-- PARAMETERISED CURSOR WILL BE BEST SUITED WHEN WE WANT TO DECLARE CURSOR ONCE,
-- BUT WANTS TO USE MULTIPLE TIMES WITH DIFFERENT NO. OF ROWS AND WANT TO DO DIFFERENT
-- PROCESSING EACH TIME.

-- CURSOR PARAMETERS CAN BE USED IN WHERE , ON AND HAVING CLAUSE OF SELECT STATEMENT ASSOCIATED WITH CURSOR.

DECLARE
	CURSOR EMP_CURSOR
	IS  
	SELECT *
	FROM MPSEMP;
BEGIN
--	FOR X IN 1..5 LOOP	
	FOR EMP_RECORD IN EMP_CURSOR LOOP  
		DBMS_OUTPUT.PUT_LINE(EMP_RECORD.DEPTNO || '  ' || 
						     RPAD(LOWER(EMP_RECORD.ENAME),10) || '  ' || 
							 TO_CHAR(EMP_RECORD.HIREDATE,'DD-MM-RRRR'));
	END LOOP;  -- CURSOR WILL BE AUTO CLOSED
END;
/