-- EXAMPLE OF PARAMERISED CURSOR

-- PARAMETERISED CURSOR WILL BE BEST SUITED WHEN WE WANT TO DECLARE CURSOR ONCE,
-- BUT WANTS TO USE MULTIPLE TIMES WITH DIFFERENT NO. OF ROWS AND WANT TO DO DIFFERENT
-- PROCESSING EACH TIME.

-- CURSOR PARAMETERS CAN BE USED IN WHERE , ON AND HAVING CLAUSE OF SELECT STATEMENT ASSOCIATED WITH CURSOR.

DECLARE
	CURSOR EMP_CURSOR
	(P_DEPTNO NUMBER DEFAULT 10) -- P_DEPTNO IS FORMAL PARAMETER WHICH CAN BE USED IN WHERE/HAVING 
	IS  
	SELECT *
	FROM MPSEMP
	WHERE DEPTNO = P_DEPTNO;
	TOTAL_SALARY NUMBER DEFAULT 0;
BEGIN
	DBMS_OUTPUT.PUT_LINE(CHR(10));
	FOR EMP_RECORD IN EMP_CURSOR(20) LOOP  -- 20 IS ACTUAL PARAMETER , CURSOR WILL BE OPENED
		DBMS_OUTPUT.PUT_LINE(EMP_RECORD.DEPTNO || '  ' || 
						     RPAD(LOWER(EMP_RECORD.ENAME),10) || '  ' || 
							 TO_CHAR(EMP_RECORD.HIREDATE,'DD-MM-RRRR'));
	END LOOP;  -- CURSOR WILL BE AUTO CLOSED
	DBMS_OUTPUT.PUT_LINE(CHR(10));
	FOR EMP_RECORD IN EMP_CURSOR(&DNO) LOOP
		DBMS_OUTPUT.PUT_LINE(EMP_RECORD.DEPTNO || '  ' ||
						    (NVL(EMP_RECORD.SAL,0)+NVL(EMP_RECORD.COMM,0))*12);
		TOTAL_SALARY := TOTAL_SALARY + (NVL(EMP_RECORD.SAL,0)+NVL(EMP_RECORD.COMM,0))*12;
	END LOOP;
	DOPL('TOTAL SALARY = ' || TOTAL_SALARY);
	DBMS_OUTPUT.PUT_LINE(CHR(10));
	FOR EMP_RECORD IN EMP_CURSOR /*()*/ LOOP
		DBMS_OUTPUT.PUT_LINE(EMP_RECORD.DEPTNO || '  ' ||
						     INITCAP(EMP_RECORD.JOB));
	END LOOP;
END;
/